--- 
title: "Атлас Российского пограничья"
author: "Лаборатория геополитических исследований ИГ РАН"
# date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [articles.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: tsamsonov/borderlands
description: "Атлас охватывает широкий круг проблем в сфере внешних связей, экономики, социальной и этнокультурной ситуации, охраны окружающей среды в приграничных регионах России и сопредельных стран"
header-includes:
   - \usepackage[T2A]{fontenc}
   - \usepackage[utf8]{inputenc}
   - \usepackage[russian]{babel}
mainfont: Open Sans
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = 'center')
knitr::opts_chunk$set(widgetframe_widgets_dir = 'widgets') 

library(leaflet)
library(classInt)
library(plotly)
library(dplyr)
library(tmap)
library(DT)
library(sf)
library(widgetframe)

source('R/map.R')
source('R/plot.R')

con = DBI::dbConnect(RSQLite::SQLite(),
                 dbname = "data/borderlands.db"
)

values = DBI::dbReadTable(con, 'VALUES') %>% bind_rows(DBI::dbReadTable(con, 'DERIVATIVES'))
indexes = DBI::dbReadTable(con, 'INDEXES')

regions = st_read('data/regions.gpkg',
                  'regions',
                  stringsAsFactors = FALSE)

coords = st_centroid(regions) %>% st_coordinates()

regions = regions %>% mutate(lon = coords[,1],
                             lat = coords[,2])

cities = st_read('data/regions.gpkg',
               'cities',
                stringsAsFactors = FALSE) %>% 
  filter(border == 1 & FEATURECLA == 'Admin-1 capital')

capitals = st_read('data/regions.gpkg',
               'cities',
                stringsAsFactors = FALSE) %>% 
  filter(border == 1 & FEATURECLA == 'Admin-0 capital')

back = st_read('data/regions.gpkg',
               'back',
                stringsAsFactors = FALSE)

borders = st_read('data/boundaries.gpkg',
                  'boundaries',
                  stringsAsFactors = FALSE)

gradients = st_read('data/boundaries.gpkg',
                    'grad_country',
                    stringsAsFactors = FALSE) %>% 
  st_set_geometry(NULL)
  
rus_border = borders %>% 
  dplyr::filter(adm0_left == 'Russia' | adm0_right == 'Russia')# %>% as('Spatial')

data = tibble::lst(values, indexes, regions, cities, capitals, 
                   back, borders, rus_border, gradients)
```

# Введение {-}

Атлас подготовлен в результате реализации исследовательского проекта Российского научного фонда «Российское пограничье: вызовы соседства» (грант №14-18-03621) и представляет собой комплексное научно-справочное картографическое произведение, призванное дать целостное представление о развитии приграничных регионов России и сопредельных стран. Атлас носит междисциплинарный и проспективный характер и допускает постоянное обновление информации. В его основу положен принцип полимаштабности: проблемы пограничья показаны на четырех уровнях – макрорегиональном, общегосударственном, региональном и локальном. Он объединяет карты, отражающие ситуацию вдоль всей линии российской границы с обеих ее сторон в европейской и азиатской частях российского пограничья и на их детально изученных на муниципальном уровне ключевых участках пограничья. Использованы передовые способы картографирования границ – от нанесения точечной экспертной информации до автоматизированной обработки данных дистанционного зондирования, пространственного анализа и интерполяции средствами ГИС.

Атлас охватывает широкий круг проблем в сфере внешних связей, экономики, социальной и этнокультурной ситуации, охраны окружающей среды в приграничных регионах России и сопредельных стран. Значительное внимание уделено влиянию на развитие приграничного сотрудничества режима и функционирования границы в целом, исторической памяти и массовых стереотипов, «фантомным границам», утратившим свои главные функции, но продолжающим влиять на отношения людей и принимаемые решения. Интегрируя разнообразную информацию в разрезе всего пограничья и его отдельных частей, атлас представляет ее в систематизированной, сопоставимой и хорошо обозримой форме.

Атлас содержит, во-первых, карты на традиционные сюжеты (дифференциации пограничья по демографическим и социально-экономическим показателям, морфологии российских границ по «возрасту» и происхождению, легитимности, этнической контрастности, экологических взаимосвязей и трансграничных угроз); во-вторых, карты на новые, неизвестные ранее темы (потенциал трансграничного сотрудничества, объекты нового строительства, роль границ в этнических и иных конфликтах, барьерность границ, повседневная жизнь и мотивы приграничной мобильности населения, историко-символический ландшафт, фантомные границы); в-третьих, карты на основе инновационных методов картографирования (плотности автодорожной сети, населенных пунктов, динамики землепользования и лесопользования).

В работе восемь разделов: «Геополитическое положение», «Население», «Уровень жизни населения», «Экономика», «Динамика трансграничных взаимодействий», «Развитие трансграничных систем и экологические угрозы», «Конфликты в приграничье», «Соотношение культурных, ментальных и институциональных границ». Атлас содержит 85 карт в разном масштабе, их аналитические описания, табличный, графический и другой дополнительный материал и ориентирован на специалистов в области международных отношений и приграничного сотрудничества, а также на широкий круг читателей, интересующихся изучением российского пограничья (пограничными исследованиями).
